"""rating change

Revision ID: 25bda6b30ae0
Revises: 1bf57a16aa06
Create Date: 2025-09-06 16:51:08.592842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25bda6b30ae0'
down_revision: Union[str, Sequence[str], None] = '1bf57a16aa06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'rating',
        existing_type=sa.BOOLEAN(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="rating::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'rating',
        existing_type=sa.Integer(),
        type_=sa.BOOLEAN(),
        existing_nullable=False,
        postgresql_using="rating::boolean"
    )
    # ### end Alembic commands ###
